/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>

#define record(n)	rs.add(otawa::riscv::R.get(n)->platformNumber())

typedef void (*write_fun_t)($(proc)_inst_t *inst, otawa::RegSet& rs);

static void otawa_write_UNKNOWN($(proc)_inst_t *inst, otawa::RegSet& rs)
{
}

$(foreach instructions)
static void otawa_write_$(IDENT)($(proc)_inst_t *inst, otawa::RegSet& rs) {
$(otawa_write)
};

$(end)

/* function table */
static write_fun_t otawa_write_table[] =
{
	otawa_write_UNKNOWN$(foreach instructions),
	otawa_write_$(IDENT)$(end)
};



/**
 * Get the OTAWA written registers of the instruction.
 */
void $(proc)_write($(proc)_inst_t *inst, otawa::RegSet& rs) {
	otawa_write_table[inst->ident](inst, rs);
}
