/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>

#define record(n)	rs.add(otawa::riscv::R.get(n)->platformNumber())

typedef void (*read_fun_t)($(proc)_inst_t *inst, otawa::RegSet& rs);

static void otawa_read_UNKNOWN($(proc)_inst_t *inst, otawa::RegSet& rs)
{
}

$(foreach instructions)
static void otawa_read_$(IDENT)($(proc)_inst_t *inst, otawa::RegSet& rs) {
$(otawa_read)
};

$(end)

/* function table */
static read_fun_t otawa_read_table[] =
{
	otawa_read_UNKNOWN$(foreach instructions),
	otawa_read_$(IDENT)$(end)
};



/**
 * Get the OTAWA read registers of the instruction.
 */
void $(proc)_read($(proc)_inst_t *inst, otawa::RegSet& rs) {
	otawa_read_table[inst->ident](inst, rs);
}
